services:
  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    volumes:
      - /var/log:/var/log
      - ./loki:/etc/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki
  promtail:
    container_name: promtail
    image: grafana/promtail:2.9.4
    ports:
      - 9080:9080
    volumes:
      - ./promtail:/etc/promtail  # Mounting local promtail-config.yml into the container
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/promtail-config.yml
    depends_on:
      - loki
    networks:
      - loki
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    networks:
      - monitoring
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      - monitoring
  grafana:
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    image: grafana/grafana
    container_name: grafana
    ports:
      - 4000:3000
    restart: unless-stopped
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring
      - loki
  db:
    image: postgres
    container_name: db
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - monitoring
  nginx:
    image: nginx:latest
    container_name: nginx
    labels:
      logging: "promtail"
      logging_jobname: "nginx"
    ports:
      - '8080:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - loki
    depends_on:
      - backend
  backend:
    restart: on-failure
    container_name: backend
    labels:
      logging: "promtail"
      logging_jobname: "backend"
    build: ./backend
    secrets:
      - db-password
    hostname: backend
    ports:
      - '81:5000'
    networks:
      - loki
    depends_on:
      db:
        condition: service_healthy

volumes:
  prom_data:
  db-data:
  grafana_data:
networks:
  monitoring:
    driver: bridge
  loki:
secrets:
  db-password:
    file: db/password.txt
